// Theme 1「縁日のガチャ屋」の駒（spec 02 §4.3）。
// 画像は assets/figures/<id>.png。無いときは emoji で代用する。

import 'defs.dart';

const kCardId = 'meishi';

const figures = <FigureDef>[
  // ── ノーマル ──
  FigureDef(id: 'koban', name: '小判', emoji: '🪙', rarity: Rarity.normal, tags: ['お金'], effects: [Add(1)]),
  FigureDef(id: 'daruma', name: 'だるま', emoji: '🔴', rarity: Rarity.normal, tags: ['縁起'], effects: [Add(1), EveryN(3, 6)]),
  FigureDef(id: 'tanuki', name: '狸の置物', emoji: '🦝', rarity: Rarity.normal, tags: ['動物'], effects: [AddPerEmptyAdjacent(1)]),
  FigureDef(id: 'kingyo', name: '金魚', emoji: '🐠', rarity: Rarity.normal, tags: ['動物', '水'], effects: [Add(1), AddIfShelfTag('水', 3, 3)]),
  FigureDef(id: 'poi', name: 'ポイ', emoji: '🏓', rarity: Rarity.normal, tags: ['道具'], effects: [Add(1), OnPlacedEatAdjacentTag('動物', 8)]),
  FigureDef(id: 'yoyo', name: '水風船', emoji: '🎈', rarity: Rarity.normal, tags: ['水', 'おもちゃ'], effects: [Add(3), Lifetime(5)]),
  FigureDef(id: 'wataame', name: 'わたあめ', emoji: '🍭', rarity: Rarity.normal, tags: ['食べ物'], effects: [Grow(1)]),
  FigureDef(id: 'takoyaki', name: 'たこ焼き', emoji: '🐙', rarity: Rarity.normal, tags: ['食べ物'], effects: [Add(2)]),
  FigureDef(id: 'ramune', name: 'ラムネ', emoji: '🧃', rarity: Rarity.normal, tags: ['食べ物', '水'], effects: [Add(1), OnPaydayGain(10)]),
  FigureDef(id: 'chochin', name: '提灯', emoji: '🏮', rarity: Rarity.normal, tags: ['飾り'], effects: [Add(1), AddIfCorner(4)]),
  FigureDef(
    id: 'maigo',
    name: '迷子',
    emoji: '😢',
    rarity: Rarity.normal,
    tags: ['人'],
    effects: [Add(-1), AddIfAdjacentId('kannushi', '神主', 13)],
  ),
  FigureDef(id: 'kakigori', name: 'かき氷', emoji: '🍧', rarity: Rarity.normal, tags: ['食べ物', '水'], effects: [Cooling(7)]),
  FigureDef(id: 'kazaguruma', name: '風車', emoji: '🌀', rarity: Rarity.normal, tags: ['おもちゃ'], effects: [EveryN(2, 6)]),
  FigureDef(id: 'uchiwa', name: 'うちわ', emoji: '🪭', rarity: Rarity.normal, tags: ['道具'], effects: [Add(2), GainOnPlaced(6)]),
  // ── レア ──
  FigureDef(id: 'kitsune', name: '狐のお面', emoji: '🦊', rarity: Rarity.rare, tags: ['縁起'], effects: [CopyBestAdjacent()]),
  FigureDef(id: 'ringoame', name: 'りんご飴', emoji: '🍎', rarity: Rarity.rare, tags: ['食べ物'], effects: [Add(1), MultAdjacentTag('食べ物', 2)]),
  FigureDef(id: 'shateki', name: '射的', emoji: '🔫', rarity: Rarity.rare, tags: ['道具'], effects: [ShootAdjacent(7)]),
  FigureDef(id: 'garagara', name: 'ガラガラ', emoji: '🎰', rarity: Rarity.rare, tags: ['道具'], effects: [Add(1), Luck(10)]),
  FigureDef(id: 'taiko', name: '太鼓', emoji: '🥁', rarity: Rarity.rare, tags: ['飾り'], effects: [BuffRow(2)]),
  FigureDef(id: 'kuji', name: 'くじ袋', emoji: '🎟️', rarity: Rarity.rare, tags: ['道具'], effects: [Add(1), SpawnEveryN(3)]),
  FigureDef(id: 'omikuji', name: 'おみくじ', emoji: '📜', rarity: Rarity.rare, tags: ['縁起'], effects: [RandomAdd(0, 9)]),
  // ── エピック ──
  FigureDef(id: 'hanabi', name: '打ち上げ花火', emoji: '🎆', rarity: Rarity.epic, tags: ['飾り'], effects: [Fuse(3, 3)]),
  FigureDef(id: 'saisen', name: 'お賽銭箱', emoji: '⛩️', rarity: Rarity.epic, tags: ['縁起'], effects: [AddPerShelfTag('縁起', 3)]),
  FigureDef(id: 'kannushi', name: '神主', emoji: '🧑‍🦲', rarity: Rarity.epic, tags: ['人'], effects: [Add(1), PaydayDiscount(20)]),
  FigureDef(id: 'kincap', name: '金のカプセル', emoji: '🌟', rarity: Rarity.epic, tags: ['道具'], effects: [OnPlacedSpawnRare(2)]),

  // ════ 縁日レベルで解禁（第1弾） ════
  // Lv2
  FigureDef(
    id: 'yakisoba',
    name: '焼きそば',
    emoji: '🍜',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 2,
    effects: [Add(1), AddIfShelfTag('人', 2, 4)],
  ),
  FigureDef(id: 'kamifusen', name: '紙風船', emoji: '🎈', rarity: Rarity.rare, tags: ['おもちゃ'], level: 2, effects: [AddPerEmptyAdjacent(2)]),
  // Lv3
  FigureDef(
    id: 'yataioji',
    name: '屋台のおっちゃん',
    emoji: '👨‍🍳',
    rarity: Rarity.rare,
    tags: ['人'],
    level: 3,
    effects: [AddPerAdjacentTag('食べ物', 3)],
  ),
  FigureDef(id: 'senkou', name: '線香花火', emoji: '🎇', rarity: Rarity.rare, tags: ['飾り'], level: 3, effects: [Grow(2), Lifetime(6)]),
  // Lv4
  FigureDef(
    id: 'yakitori',
    name: '焼き鳥',
    emoji: '🍢',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 4,
    effects: [Add(1), AddIfShelfTag('食べ物', 4, 5)],
  ),
  FigureDef(
    id: 'kame',
    name: '亀',
    emoji: '🐢',
    rarity: Rarity.normal,
    tags: ['動物', '水'],
    level: 4,
    effects: [Add(1), AddPerAdjacentTag('水', 2)],
  ),
  FigureDef(id: 'kinchaku', name: '巾着袋', emoji: '👛', rarity: Rarity.rare, tags: ['お金'], level: 4, effects: [AddPerShelfTag('お金', 2)]),
  FigureDef(
    id: 'yukata',
    name: '浴衣の娘',
    emoji: '👘',
    rarity: Rarity.rare,
    tags: ['人'],
    level: 4,
    effects: [Add(1), AddPerShelfTag('飾り', 2)],
  ),
  FigureDef(id: 'mikoshi', name: 'お神輿', emoji: '⛩️', rarity: Rarity.epic, tags: ['縁起', '人'], level: 4, effects: [AddPerShelfTag('人', 4)]),
  // Lv5
  // 招き猫 waits until there is more お金 to double (小判, then 巾着袋 at Lv4)
  FigureDef(id: 'maneki', name: '招き猫', emoji: '🐱', rarity: Rarity.rare, tags: ['縁起', '動物'], level: 5, effects: [Add(1), MultAdjacentTag('お金', 2)]),
  FigureDef(id: 'chocoban', name: 'チョコバナナ', emoji: '🍌', rarity: Rarity.normal, tags: ['食べ物'], level: 5, effects: [Add(1), AddIfAlone(6)]),
  FigureDef(id: 'suzu', name: '鈴', emoji: '🔔', rarity: Rarity.normal, tags: ['縁起'], level: 5, effects: [AddPerShelfFigures(3, 1)]),
  FigureDef(id: 'wanage', name: '輪投げ', emoji: '⭕', rarity: Rarity.rare, tags: ['おもちゃ'], level: 5, effects: [BuffColumn(3)]),
  FigureDef(
    id: 'kingyobachi',
    name: '金魚鉢',
    emoji: '🫙',
    rarity: Rarity.rare,
    tags: ['水'],
    level: 5,
    effects: [Add(1), MultAdjacentTag('水', 2)],
  ),
  FigureDef(
    id: 'shishimai',
    name: '獅子舞',
    emoji: '🦁',
    rarity: Rarity.epic,
    tags: ['縁起'],
    level: 5,
    effects: [Add(3), OnPlacedEatAdjacentTag('のろい', 42)],
  ),
  // Lv6
  FigureDef(
    id: 'hyottoko',
    name: 'ひょっとこのお面',
    emoji: '🎭',
    rarity: Rarity.normal,
    tags: ['縁起', '飾り'],
    level: 6,
    effects: [AddPerAdjacentTag('人', 4)],
  ),
  FigureDef(
    id: 'superball',
    name: 'スーパーボール',
    emoji: '🔮',
    rarity: Rarity.normal,
    tags: ['おもちゃ'],
    level: 6,
    effects: [Add(2), AddIfShelfTag('おもちゃ', 3, 6)],
  ),
  FigureDef(id: 'kumade', name: '熊手', emoji: '🧹', rarity: Rarity.epic, tags: ['縁起', 'お金'], level: 6, effects: [MultAdjacentTag('縁起', 3)]),
  FigureDef(
    id: 'ebisu',
    name: '恵比寿さま',
    emoji: '🎣',
    rarity: Rarity.legend,
    tags: ['縁起', '人'],
    level: 6,
    effects: [Add(3), PaydayDiscount(35)],
  ),
  // Lv7
  FigureDef(id: 'yagura', name: 'やぐら', emoji: '🗼', rarity: Rarity.epic, tags: ['飾り'], level: 7, effects: [BuffColumn(5)]),
  FigureDef(
    id: 'benzaiten',
    name: '弁財天',
    emoji: '🪕',
    rarity: Rarity.legend,
    tags: ['縁起', '人'],
    level: 7,
    effects: [Add(3), MultShelfTag('食べ物', 3)],
  ),

  // ════ 縁日レベルで解禁（第2弾） ════
  // Lv8
  FigureDef(
    id: 'ikayaki',
    name: 'イカ焼き',
    emoji: '🦑',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 8,
    effects: [Add(1), AddPerAdjacentTag('食べ物', 1)],
  ),
  FigureDef(id: 'jagabata', name: 'じゃがバター', emoji: '🥔', rarity: Rarity.normal, tags: ['食べ物'], level: 8, effects: [Add(3), AddIfCorner(3)]),
  FigureDef(id: 'menko', name: 'めんこ', emoji: '🃏', rarity: Rarity.normal, tags: ['おもちゃ'], level: 8, effects: [RandomAdd(0, 7)]),
  FigureDef(
    id: 'demekin',
    name: '黒出目金',
    emoji: '🐟',
    rarity: Rarity.rare,
    tags: ['動物', '水'],
    level: 8,
    effects: [Add(1), AddPerShelfTag('水', 3)],
  ),
  FigureDef(id: 'katanuki', name: '型抜き', emoji: '🍬', rarity: Rarity.rare, tags: ['道具'], level: 8, effects: [EveryN(4, 21)]),
  FigureDef(
    id: 'tengu',
    name: '天狗のお面',
    emoji: '👺',
    rarity: Rarity.epic,
    tags: ['縁起', '飾り'],
    level: 8,
    effects: [Add(1), MultAdjacentTag('飾り', 3)],
  ),
  // Lv9
  FigureDef(
    id: 'karaage',
    name: '唐揚げ',
    emoji: '🍗',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 9,
    effects: [Add(1), AddIfShelfTag('食べ物', 3, 4)],
  ),
  FigureDef(id: 'kendama', name: 'けん玉', emoji: '🪀', rarity: Rarity.normal, tags: ['おもちゃ'], level: 9, effects: [EveryN(3, 10)]),
  FigureDef(
    id: 'hiyoko',
    name: 'ひよこ',
    emoji: '🐤',
    rarity: Rarity.normal,
    tags: ['動物'],
    level: 9,
    effects: [Grow(1), AddPerAdjacentTag('動物', 1)],
  ),
  FigureDef(
    id: 'wagasa',
    name: '和傘',
    emoji: '⛱️',
    rarity: Rarity.rare,
    tags: ['飾り'],
    level: 9,
    effects: [AddPerEmptyAdjacent(1), BuffRow(1)],
  ),
  FigureDef(
    id: 'dango',
    name: '三色だんご',
    emoji: '🍡',
    rarity: Rarity.rare,
    tags: ['食べ物'],
    level: 9,
    effects: [Add(1), AddPerShelfTag('食べ物', 1)],
  ),
  FigureDef(
    id: 'tanabata',
    name: '七夕飾り',
    emoji: '🎋',
    rarity: Rarity.epic,
    tags: ['飾り', '縁起'],
    level: 9,
    effects: [AddPerShelfTag('飾り', 4)],
  ),
  // Lv10
  FigureDef(id: 'mizuame', name: '水あめ', emoji: '🍯', rarity: Rarity.normal, tags: ['食べ物'], level: 10, effects: [Grow(1), AddIfAlone(3)]),
  FigureDef(id: 'fue', name: '篠笛', emoji: '🪈', rarity: Rarity.normal, tags: ['道具'], level: 10, effects: [BuffRow(1)]),
  FigureDef(
    id: 'usagi',
    name: 'うさぎのお面',
    emoji: '🐰',
    rarity: Rarity.normal,
    tags: ['縁起', '飾り'],
    level: 10,
    effects: [Add(1), AddIfCorner(4)],
  ),
  FigureDef(
    id: 'sukuiya',
    name: '金魚すくいのおじさん',
    emoji: '🧓',
    rarity: Rarity.rare,
    tags: ['人'],
    level: 10,
    effects: [AddPerShelfTag('動物', 3)],
  ),
  FigureDef(
    id: 'hanabishi',
    name: '花火師',
    emoji: '🧨',
    rarity: Rarity.rare,
    tags: ['人'],
    level: 10,
    effects: [Add(1), MultAdjacentTag('飾り', 2)],
  ),
  FigureDef(
    id: 'hotei',
    name: '布袋さま',
    emoji: '🎒',
    rarity: Rarity.legend,
    tags: ['縁起', '人'],
    level: 10,
    effects: [AddPerShelfFigures(1, 1)],
  ),
  // Lv11
  FigureDef(
    id: 'tomorokoshi',
    name: '焼きとうもろこし',
    emoji: '🌽',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 11,
    effects: [Add(3), GainOnPlaced(6)],
  ),
  FigureDef(
    id: 'shabondama',
    name: 'シャボン玉',
    emoji: '🫧',
    rarity: Rarity.normal,
    tags: ['おもちゃ', '水'],
    level: 11,
    effects: [Add(6), Lifetime(3)],
  ),
  FigureDef(
    id: 'hotaru',
    name: 'ホタル',
    emoji: '✨',
    rarity: Rarity.normal,
    tags: ['動物'],
    level: 11,
    effects: [Add(2), AddPerEmptyAdjacent(2)],
  ),
  FigureDef(
    id: 'okame',
    name: 'おかめのお面',
    emoji: '😊',
    rarity: Rarity.rare,
    tags: ['縁起', '飾り'],
    level: 11,
    effects: [Add(2), AddIfAdjacentId('hyottoko', 'ひょっとこのお面', 18)],
  ),
  FigureDef(id: 'taikoboy', name: '太鼓たたき', emoji: '🥢', rarity: Rarity.rare, tags: ['人'], level: 11, effects: [AddPerAdjacentTag('飾り', 4)]),
  FigureDef(
    id: 'bishamon',
    name: '毘沙門天',
    emoji: '🛡️',
    rarity: Rarity.legend,
    tags: ['縁起', '人'],
    level: 11,
    effects: [MultShelfTag('人', 2)],
  ),
  // Lv12
  // 大黒さま (everything ×2) is too strong for the first festivals
  FigureDef(id: 'daikoku', name: '大黒さま', emoji: '🎎', rarity: Rarity.legend, tags: ['縁起', '人'], level: 12, effects: [MultAll(2)]),
  FigureDef(
    id: 'ichigoame',
    name: 'いちご飴',
    emoji: '🍓',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 12,
    effects: [AddPerAdjacentTag('食べ物', 3)],
  ),
  FigureDef(
    id: 'mizudeppo',
    name: '水鉄砲',
    emoji: '🔫',
    rarity: Rarity.normal,
    tags: ['おもちゃ', '水'],
    level: 12,
    effects: [Add(1), AddPerShelfTag('水', 1)],
  ),
  FigureDef(id: 'kabuto', name: 'カブトムシ', emoji: '🪲', rarity: Rarity.normal, tags: ['動物'], level: 12, effects: [EveryN(3, 12)]),
  FigureDef(
    id: 'ranchu',
    name: 'らんちゅう',
    emoji: '🐡',
    rarity: Rarity.rare,
    tags: ['動物', '水'],
    level: 12,
    effects: [Add(3), AddIfShelfTag('水', 4, 9)],
  ),
  FigureDef(id: 'omamori', name: 'お守り', emoji: '🧧', rarity: Rarity.rare, tags: ['縁起'], level: 12, effects: [Add(1), Luck(8)]),
  FigureDef(id: 'fujin', name: '風神', emoji: '🌬️', rarity: Rarity.epic, tags: ['縁起'], level: 12, effects: [BuffRow(4)]),
  // Lv13
  FigureDef(id: 'crepe', name: 'クレープ', emoji: '🥞', rarity: Rarity.normal, tags: ['食べ物'], level: 13, effects: [Cooling(12)]),
  FigureDef(
    id: 'otedama',
    name: 'お手玉',
    emoji: '🧶',
    rarity: Rarity.normal,
    tags: ['おもちゃ'],
    level: 13,
    effects: [Add(2), AddPerShelfTag('おもちゃ', 2)],
  ),
  FigureDef(id: 'suzumushi', name: '鈴虫', emoji: '🦗', rarity: Rarity.normal, tags: ['動物'], level: 13, effects: [EveryN(2, 6)]),
  FigureDef(id: 'toro', name: '灯籠流し', emoji: '🏮', rarity: Rarity.rare, tags: ['飾り', '水'], level: 13, effects: [Add(2), Fuse(4, 2)]),
  FigureDef(id: 'miko', name: '巫女さん', emoji: '⛩️', rarity: Rarity.rare, tags: ['人', '縁起'], level: 13, effects: [AddPerShelfTag('縁起', 3)]),
  FigureDef(id: 'raijin', name: '雷神', emoji: '⚡', rarity: Rarity.epic, tags: ['縁起'], level: 13, effects: [RandomAdd(0, 30)]),
  // Lv14
  FigureDef(
    id: 'kushikatsu',
    name: '串カツ',
    emoji: '🍢',
    rarity: Rarity.normal,
    tags: ['食べ物'],
    level: 14,
    effects: [Add(3), AddPerAdjacentTag('人', 2)],
  ),
  FigureDef(
    id: 'darumaotoshi',
    name: 'だるま落とし',
    emoji: '🎯',
    rarity: Rarity.normal,
    tags: ['おもちゃ'],
    level: 14,
    effects: [Add(2), EveryN(3, 10)],
  ),
  FigureDef(
    id: 'inari',
    name: 'お稲荷さん',
    emoji: '🦊',
    rarity: Rarity.rare,
    tags: ['縁起', '動物'],
    level: 14,
    effects: [AddPerShelfTag('動物', 3)],
  ),
  FigureDef(id: 'ninja', name: '忍者', emoji: '🥷', rarity: Rarity.rare, tags: ['人'], level: 14, effects: [Add(2), GainOnPlaced(25)]),
  FigureDef(id: 'hozuki', name: 'ほおずき', emoji: '🏮', rarity: Rarity.rare, tags: ['飾り'], level: 14, effects: [Add(3), AddIfCorner(8)]),
  FigureDef(id: 'kirin', name: '麒麟', emoji: '🦌', rarity: Rarity.legend, tags: ['縁起', '動物'], level: 14, effects: [Add(8), Luck(20)]),
  // Lv15
  FigureDef(
    id: 'ougonkingyo',
    name: '黄金の金魚',
    emoji: '🐠',
    rarity: Rarity.epic,
    tags: ['動物', '水', 'お金'],
    level: 15,
    effects: [AddPerShelfTag('水', 5)],
  ),
  FigureDef(
    id: 'takarabune',
    name: '宝船',
    emoji: '🚢',
    rarity: Rarity.legend,
    tags: ['縁起', 'お金'],
    level: 15,
    effects: [MultShelfTag('お金', 4)],
  ),
  FigureDef(id: 'ryu', name: '龍', emoji: '🐉', rarity: Rarity.legend, tags: ['縁起', '動物'], level: 15, effects: [MultShelfTag('縁起', 3)]),
  FigureDef(
    id: 'kinmaneki',
    name: '金の招き猫',
    emoji: '🐈',
    rarity: Rarity.epic,
    tags: ['縁起', '動物', 'お金'],
    level: 15,
    effects: [Add(2), MultAdjacentTag('お金', 3)],
  ),
  FigureDef(id: 'hannya', name: '般若のお面', emoji: '👹', rarity: Rarity.epic, tags: ['飾り'], level: 15, effects: [Add(7), AddIfAlone(14)]),
  FigureDef(
    id: 'kintaro',
    name: '金太郎',
    emoji: '🐻',
    rarity: Rarity.rare,
    tags: ['人'],
    level: 15,
    effects: [Add(5), AddPerAdjacentTag('動物', 3)],
  ),

  // ── のろい（ガチャからは出ない。親分が置いていく） ──
  FigureDef(id: kCardId, name: '親分の名刺', emoji: '📛', rarity: Rarity.curse, tags: ['のろい'], effects: [Add(-2), OnRemovedGain(20)]),
];

final figureById = {for (final f in figures) f.id: f};
