// 推し祭壇ガチャの駒（グッズ）。効果の数字は 縁日版（../gacha_rogue）の対応する駒と同じ。
// 生成元：art/goods.py（名前・タグ・絵の説明はそちらで直して `python3 art/goods.py figures`）。
// 画像は assets/figures/<id>.webp（art/slice.py）。無いときは emoji で代用する。
// タグ：ひなた・しずく・こはる・よる・もも（推し）／ファン・お金・ぱれにゃん・応援／のろい（つむぎの注意書き）

import 'defs.dart';

const kCardId = 'tokusoku';

const figures = <FigureDef>[
  FigureDef(id: 'coin', name: 'ハートのメダル', emoji: '🪙', rarity: Rarity.normal, tags: ['お金'], effects: [Add(1)]),
  FigureDef(id: 'hinata_badge', name: 'ひなたの缶バッジ', emoji: '🔴', rarity: Rarity.normal, tags: ['ひなた'], cast: ['ひなた'], effects: [Add(1), EveryN(3, 6)]),
  FigureDef(id: 'momo_badge', name: 'ももの缶バッジ', emoji: '🩷', rarity: Rarity.normal, tags: ['もも'], cast: ['もも'], effects: [AddPerEmptyAdjacent(1)]),
  FigureDef(id: 'shizumomo_strap', name: 'しずもものラバスト', emoji: '🫧', rarity: Rarity.normal, tags: ['もも', 'しずく'], cast: ['しずく', 'もも'], effects: [Add(1), AddIfShelfTag('しずく', 3, 3)]),
  FigureDef(id: 'trade_file', name: '交換用バインダー', emoji: '📒', rarity: Rarity.normal, tags: ['応援'], effects: [Add(1), OnPlacedEatAdjacentTag('もも', 8)]),
  FigureDef(id: 'aqua_balloon', name: 'しずく色のバルーン', emoji: '🎈', rarity: Rarity.normal, tags: ['しずく', 'ぱれにゃん'], cast: ['しずく'], effects: [Add(3), Lifetime(5)]),
  FigureDef(id: 'koharu_badge', name: 'こはるの缶バッジ', emoji: '🟡', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], effects: [Grow(1)]),
  FigureDef(id: 'koharu_keyholder', name: 'こはるのアクキー', emoji: '🍩', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], effects: [Add(2)]),
  FigureDef(id: 'collab_drink', name: 'コラボカフェのドリンク', emoji: '🥤', rarity: Rarity.normal, tags: ['こはる', 'しずく'], cast: ['しずく', 'こはる'], effects: [Add(1), OnPaydayGain(10)]),
  FigureDef(id: 'yoru_badge', name: 'よるの缶バッジ', emoji: '🟣', rarity: Rarity.normal, tags: ['よる'], cast: ['よる'], effects: [Add(1), AddIfCorner(4)]),
  FigureDef(
    id: 'shinki',
    name: '新規のオタク',
    emoji: '😰',
    rarity: Rarity.normal,
    tags: ['ファン'],
    effects: [Add(-1), AddIfAdjacentId('kosan', '古参オタク', 13)],
  ),
  FigureDef(id: 'collab_kakigori', name: 'コラボかき氷', emoji: '🍧', rarity: Rarity.normal, tags: ['こはる', 'しずく'], cast: ['しずく', 'こはる'], effects: [Cooling(7)]),
  FigureDef(id: 'nyan_badge', name: 'ぱれにゃん缶バッジ', emoji: '🐱', rarity: Rarity.normal, tags: ['ぱれにゃん'], effects: [EveryN(2, 6)]),
  FigureDef(id: 'oshi_uchiwa', name: '推しうちわ', emoji: '🪭', rarity: Rarity.normal, tags: ['応援'], effects: [Add(2), GainOnPlaced(6)]),
  FigureDef(id: 'hinata_mirror', name: 'ひなたのまねっこアクスタ', emoji: '🪞', rarity: Rarity.rare, tags: ['ひなた'], cast: ['ひなた'], effects: [CopyBestAdjacent()]),
  FigureDef(id: 'koharu_acsta', name: 'こはるのアクスタ', emoji: '🍰', rarity: Rarity.rare, tags: ['こはる'], cast: ['こはる'], effects: [Add(1), MultAdjacentTag('こはる', 2)]),
  FigureDef(id: 'flea', name: 'フリマ出品', emoji: '📦', rarity: Rarity.rare, tags: ['応援'], effects: [ShootAdjacent(7)]),
  FigureDef(id: 'gacha_charm', name: 'ガチャ運のお守り', emoji: '🧧', rarity: Rarity.rare, tags: ['応援'], effects: [Add(1), Luck(10)]),
  FigureDef(id: 'yoru_penlight', name: 'よるのペンライト', emoji: '🔦', rarity: Rarity.rare, tags: ['よる'], cast: ['よる'], effects: [BuffRow(2)]),
  FigureDef(id: 'blind_bag', name: 'ランダム缶バッジ', emoji: '🎁', rarity: Rarity.rare, tags: ['応援'], effects: [Add(1), SpawnEveryN(3)]),
  FigureDef(id: 'hinata_photo', name: 'ひなたのブロマイド', emoji: '📸', rarity: Rarity.rare, tags: ['ひなた'], cast: ['ひなた'], effects: [RandomAdd(0, 9)]),
  FigureDef(id: 'yoru_tape', name: 'ライブの銀テープ', emoji: '🎊', rarity: Rarity.epic, tags: ['よる'], cast: ['よる'], effects: [Fuse(3, 3)]),
  FigureDef(id: 'hinata_altar', name: 'ひなたの祭壇', emoji: '⛩️', rarity: Rarity.epic, tags: ['ひなた'], cast: ['ひなた'], effects: [AddPerShelfTag('ひなた', 3)]),
  FigureDef(id: 'kosan', name: '古参オタク', emoji: '😎', rarity: Rarity.epic, tags: ['ファン'], effects: [Add(1), PaydayDiscount(20)]),
  FigureDef(id: 'kincap', name: '金のカプセル', emoji: '🌟', rarity: Rarity.epic, tags: ['応援'], effects: [OnPlacedSpawnRare(2)]),
  FigureDef(
    id: 'koharu_cookie',
    name: 'こはるのクッキー缶',
    emoji: '🍪',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 2,
    effects: [Add(1), AddIfShelfTag('ファン', 2, 4)],
  ),
  FigureDef(id: 'nyan_balloon', name: 'ぱれにゃん風船', emoji: '🎈', rarity: Rarity.rare, tags: ['ぱれにゃん'], level: 2, effects: [AddPerEmptyAdjacent(2)]),
  FigureDef(
    id: 'cafe_master',
    name: 'コラボカフェの店長',
    emoji: '🧑‍🍳',
    rarity: Rarity.rare,
    tags: ['ファン'],
    level: 3,
    effects: [AddPerAdjacentTag('こはる', 3)],
  ),
  FigureDef(id: 'yoru_candle', name: 'よるのキャンドル', emoji: '🕯️', rarity: Rarity.rare, tags: ['よる'], cast: ['よる'], level: 3, effects: [Grow(2), Lifetime(6)]),
  FigureDef(
    id: 'koharu_card',
    name: 'こはるのトレカ',
    emoji: '🃏',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 4,
    effects: [Add(1), AddIfShelfTag('こはる', 4, 5)],
  ),
  FigureDef(
    id: 'shizumomo_acsta',
    name: 'しずもものペアアクスタ',
    emoji: '🤝',
    rarity: Rarity.normal,
    tags: ['もも', 'しずく'], cast: ['しずく', 'もも'],
    level: 4,
    effects: [Add(1), AddPerAdjacentTag('しずく', 2)],
  ),
  FigureDef(id: 'oshi_bank', name: '推し貯金箱', emoji: '🐷', rarity: Rarity.rare, tags: ['お金'], level: 4, effects: [AddPerShelfTag('お金', 2)]),
  FigureDef(
    id: 'yoru_tan',
    name: 'よる担のオタク',
    emoji: '💜',
    rarity: Rarity.rare,
    tags: ['ファン'], cast: ['よる'],
    level: 4,
    effects: [Add(1), AddPerShelfTag('よる', 2)],
  ),
  FigureDef(id: 'hinata_akushu', name: 'ひなたの握手会', emoji: '🤝', rarity: Rarity.epic, tags: ['ひなた', 'ファン'], cast: ['ひなた'], level: 4, effects: [AddPerShelfTag('ファン', 4)]),
  FigureDef(id: 'hinamomo_maneki', name: '招き猫ポーズのひなもも', emoji: '🐱', rarity: Rarity.rare, tags: ['ひなた', 'もも'], cast: ['ひなた', 'もも'], level: 5, effects: [Add(1), MultAdjacentTag('お金', 2)]),
  FigureDef(id: 'koharu_nui', name: 'こはるのおやつぬい', emoji: '🧸', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], level: 5, effects: [Add(1), AddIfAlone(6)]),
  FigureDef(id: 'hinata_bell', name: 'ひなたの鈴キーホルダー', emoji: '🔔', rarity: Rarity.normal, tags: ['ひなた'], cast: ['ひなた'], level: 5, effects: [AddPerShelfFigures(3, 1)]),
  FigureDef(id: 'nyan_tower', name: 'ぱれにゃんタワー', emoji: '🗼', rarity: Rarity.rare, tags: ['ぱれにゃん'], level: 5, effects: [BuffColumn(3)]),
  FigureDef(
    id: 'shizuku_acsta',
    name: 'しずくのアクスタ',
    emoji: '💧',
    rarity: Rarity.rare,
    tags: ['しずく'], cast: ['しずく'],
    level: 5,
    effects: [Add(1), MultAdjacentTag('しずく', 2)],
  ),
  FigureDef(
    id: 'hinata_letter',
    name: 'ひなたの直筆メッセージ',
    emoji: '💌',
    rarity: Rarity.epic,
    tags: ['ひなた'], cast: ['ひなた'],
    level: 5,
    effects: [Add(3), OnPlacedEatAdjacentTag('のろい', 42)],
  ),
  FigureDef(
    id: 'hinayoru_board',
    name: 'ひなよるのファンサボード',
    emoji: '🪧',
    rarity: Rarity.normal,
    tags: ['ひなた', 'よる'], cast: ['ひなた', 'よる'],
    level: 6,
    effects: [AddPerAdjacentTag('ファン', 4)],
  ),
  FigureDef(
    id: 'nyan_squeeze',
    name: 'ぱれにゃんスクイーズ',
    emoji: '🍡',
    rarity: Rarity.normal,
    tags: ['ぱれにゃん'],
    level: 6,
    effects: [Add(2), AddIfShelfTag('ぱれにゃん', 3, 6)],
  ),
  FigureDef(id: 'hinata_gold', name: 'ひなたのゴールド缶バッジ', emoji: '🥇', rarity: Rarity.epic, tags: ['ひなた', 'お金'], cast: ['ひなた'], level: 6, effects: [MultAdjacentTag('ひなた', 3)]),
  FigureDef(
    id: 'hinata_live',
    name: 'ひなたのソロライブ',
    emoji: '🎤',
    rarity: Rarity.legend,
    tags: ['ひなた', 'ファン'], cast: ['ひなた'],
    level: 6,
    effects: [Add(3), PaydayDiscount(35)],
  ),
  FigureDef(id: 'yoru_shelf', name: 'よるのゴシック祭壇棚', emoji: '🗄️', rarity: Rarity.epic, tags: ['よる'], cast: ['よる'], level: 7, effects: [BuffColumn(5)]),
  FigureDef(
    id: 'hinakoha_stream',
    name: 'ひなこはのお料理配信',
    emoji: '🍳',
    rarity: Rarity.legend,
    tags: ['ひなた', 'ファン'], cast: ['ひなた', 'こはる'],
    level: 7,
    effects: [Add(3), MultShelfTag('こはる', 3)],
  ),
  FigureDef(
    id: 'koharu_snack',
    name: 'こはるのおやつ瓶',
    emoji: '🍬',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 8,
    effects: [Add(1), AddPerAdjacentTag('こはる', 1)],
  ),
  FigureDef(id: 'koharu_cushion', name: 'こはるのクッション', emoji: '🛋️', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], level: 8, effects: [Add(3), AddIfCorner(3)]),
  FigureDef(id: 'nyan_card', name: 'ぱれにゃんトレカ', emoji: '🎴', rarity: Rarity.normal, tags: ['ぱれにゃん'], level: 8, effects: [RandomAdd(0, 7)]),
  FigureDef(
    id: 'shizumomo_hoodie',
    name: 'しずもものおそろいパーカー',
    emoji: '🧥',
    rarity: Rarity.rare,
    tags: ['もも', 'しずく'], cast: ['しずく', 'もも'],
    level: 8,
    effects: [Add(1), AddPerShelfTag('しずく', 3)],
  ),
  FigureDef(id: 'lottery', name: 'ライブの抽選券', emoji: '🎫', rarity: Rarity.rare, tags: ['応援'], level: 8, effects: [EveryN(4, 21)]),
  FigureDef(
    id: 'hinayoru_costume',
    name: 'ひなよるのユニット衣装',
    emoji: '👗',
    rarity: Rarity.epic,
    tags: ['ひなた', 'よる'], cast: ['ひなた', 'よる'],
    level: 8,
    effects: [Add(1), MultAdjacentTag('よる', 3)],
  ),
  FigureDef(
    id: 'koharu_tote',
    name: 'こはるのランチトート',
    emoji: '👜',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 9,
    effects: [Add(1), AddIfShelfTag('こはる', 3, 4)],
  ),
  FigureDef(id: 'nyan_music', name: 'ぱれにゃんオルゴール', emoji: '🎶', rarity: Rarity.normal, tags: ['ぱれにゃん'], level: 9, effects: [EveryN(3, 10)]),
  FigureDef(
    id: 'momo_mini',
    name: 'もものミニぬい',
    emoji: '🧸',
    rarity: Rarity.normal,
    tags: ['もも'], cast: ['もも'],
    level: 9,
    effects: [Grow(1), AddPerAdjacentTag('もも', 1)],
  ),
  FigureDef(
    id: 'yoru_parasol',
    name: 'よるの日傘',
    emoji: '☂️',
    rarity: Rarity.rare,
    tags: ['よる'], cast: ['よる'],
    level: 9,
    effects: [AddPerEmptyAdjacent(1), BuffRow(1)],
  ),
  FigureDef(
    id: 'koharu_sweets',
    name: 'こはるのおやつアクスタ',
    emoji: '🍡',
    rarity: Rarity.rare,
    tags: ['こはる'], cast: ['こはる'],
    level: 9,
    effects: [Add(1), AddPerShelfTag('こはる', 1)],
  ),
  FigureDef(
    id: 'hinayoru_tapestry',
    name: 'ひなよるの星空タペストリー',
    emoji: '🌌',
    rarity: Rarity.epic,
    tags: ['よる', 'ひなた'], cast: ['ひなた', 'よる'],
    level: 9,
    effects: [AddPerShelfTag('よる', 4)],
  ),
  FigureDef(id: 'koharu_honey', name: 'こはるのはちみつキャンドル', emoji: '🍯', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], level: 10, effects: [Grow(1), AddIfAlone(3)]),
  FigureDef(id: 'penlight', name: 'ペンライト', emoji: '🔦', rarity: Rarity.normal, tags: ['応援'], level: 10, effects: [BuffRow(1)]),
  FigureDef(
    id: 'hinayoru_ears',
    name: 'ひなよるのうさ耳カチューシャ',
    emoji: '🐰',
    rarity: Rarity.normal,
    tags: ['ひなた', 'よる'], cast: ['ひなた', 'よる'],
    level: 10,
    effects: [Add(1), AddIfCorner(4)],
  ),
  FigureDef(
    id: 'momo_tan',
    name: 'もも担のオタク',
    emoji: '💗',
    rarity: Rarity.rare,
    tags: ['ファン'], cast: ['もも'],
    level: 10,
    effects: [AddPerShelfTag('もも', 3)],
  ),
  FigureDef(
    id: 'light_staff',
    name: '照明スタッフ',
    emoji: '💡',
    rarity: Rarity.rare,
    tags: ['ファン'],
    level: 10,
    effects: [Add(1), MultAdjacentTag('よる', 2)],
  ),
  FigureDef(
    id: 'hinata_tour',
    name: 'ひなたの全国ツアー',
    emoji: '🚌',
    rarity: Rarity.legend,
    tags: ['ひなた', 'ファン'], cast: ['ひなた'],
    level: 10,
    effects: [AddPerShelfFigures(1, 1)],
  ),
  FigureDef(
    id: 'koharu_popcorn',
    name: 'こはるのポップコーン',
    emoji: '🍿',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 11,
    effects: [Add(3), GainOnPlaced(6)],
  ),
  FigureDef(
    id: 'shizuku_bubble',
    name: 'しずく色のシャボン玉',
    emoji: '🫧',
    rarity: Rarity.normal,
    tags: ['ぱれにゃん', 'しずく'], cast: ['しずく'],
    level: 11,
    effects: [Add(6), Lifetime(3)],
  ),
  FigureDef(
    id: 'momo_ears',
    name: 'もものネコ耳カチューシャ',
    emoji: '🐾',
    rarity: Rarity.normal,
    tags: ['もも'], cast: ['もも'],
    level: 11,
    effects: [Add(2), AddPerEmptyAdjacent(2)],
  ),
  FigureDef(
    id: 'hinayoru_cheki',
    name: 'ひなよるのペアチェキ',
    emoji: '📷',
    rarity: Rarity.rare,
    tags: ['ひなた', 'よる'], cast: ['ひなた', 'よる'],
    level: 11,
    effects: [Add(2), AddIfAdjacentId('hinayoru_board', 'ひなよるのファンサボード', 18)],
  ),
  FigureDef(id: 'yoru_cameko', name: 'よる推しのカメコ', emoji: '📹', rarity: Rarity.rare, tags: ['ファン'], cast: ['よる'], level: 11, effects: [AddPerAdjacentTag('よる', 4)]),
  FigureDef(
    id: 'hinata_fanmeet',
    name: 'ひなたのファンミーティング',
    emoji: '🎉',
    rarity: Rarity.legend,
    tags: ['ひなた', 'ファン'], cast: ['ひなた'],
    level: 11,
    effects: [MultShelfTag('ファン', 2)],
  ),
  FigureDef(id: 'unit_panel', name: 'ぷりパレ全員の等身大パネル', emoji: '🌈', rarity: Rarity.legend, tags: ['ひなた', 'ファン'], cast: ['ひなた', 'しずく', 'こはる', 'よる', 'もも'], level: 12, effects: [MultAll(2)]),
  FigureDef(
    id: 'koharu_milk',
    name: 'こはるのいちごミルク',
    emoji: '🍓',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 12,
    effects: [AddPerAdjacentTag('こはる', 3)],
  ),
  FigureDef(
    id: 'nyan_bottle',
    name: 'ぱれにゃんボトル',
    emoji: '🍼',
    rarity: Rarity.normal,
    tags: ['ぱれにゃん', 'しずく'], cast: ['しずく'],
    level: 12,
    effects: [Add(1), AddPerShelfTag('しずく', 1)],
  ),
  FigureDef(id: 'momo_capsule', name: 'もものカプセルトイ', emoji: '🥚', rarity: Rarity.normal, tags: ['もも'], cast: ['もも'], level: 12, effects: [EveryN(3, 12)]),
  FigureDef(
    id: 'shizumomo_badge',
    name: 'しずもものペア缶バッジ',
    emoji: '💞',
    rarity: Rarity.rare,
    tags: ['もも', 'しずく'], cast: ['しずく', 'もも'],
    level: 12,
    effects: [Add(3), AddIfShelfTag('しずく', 4, 9)],
  ),
  FigureDef(id: 'hinata_charm', name: 'ひなたの手作りお守り', emoji: '🍀', rarity: Rarity.rare, tags: ['ひなた'], cast: ['ひなた'], level: 12, effects: [Add(1), Luck(8)]),
  FigureDef(id: 'hinata_mic', name: 'ひなたのセンターマイク', emoji: '🎙️', rarity: Rarity.epic, tags: ['ひなた'], cast: ['ひなた'], level: 12, effects: [BuffRow(4)]),
  FigureDef(id: 'koharu_crepe', name: 'コラボクレープ', emoji: '🥞', rarity: Rarity.normal, tags: ['こはる'], cast: ['こはる'], level: 13, effects: [Cooling(12)]),
  FigureDef(
    id: 'nyan_mini',
    name: 'ぱれにゃんのミニぬい',
    emoji: '🐾',
    rarity: Rarity.normal,
    tags: ['ぱれにゃん'],
    level: 13,
    effects: [Add(2), AddPerShelfTag('ぱれにゃん', 2)],
  ),
  FigureDef(id: 'momo_ribbon', name: 'もものリボン', emoji: '🎀', rarity: Rarity.normal, tags: ['もも'], cast: ['もも'], level: 13, effects: [EveryN(2, 6)]),
  FigureDef(id: 'shizuyoru_candle', name: 'しずよるの夜景キャンドル', emoji: '🏮', rarity: Rarity.rare, tags: ['よる', 'しずく'], cast: ['しずく', 'よる'], level: 13, effects: [Add(2), Fuse(4, 2)]),
  FigureDef(id: 'hinata_tan', name: 'ひなた担のオタク', emoji: '❤️', rarity: Rarity.rare, tags: ['ファン', 'ひなた'], cast: ['ひなた'], level: 13, effects: [AddPerShelfTag('ひなた', 3)]),
  FigureDef(id: 'hinata_secret', name: 'ひなたのシークレット缶バッジ', emoji: '🌈', rarity: Rarity.epic, tags: ['ひなた'], cast: ['ひなた'], level: 13, effects: [RandomAdd(0, 30)]),
  FigureDef(
    id: 'koharu_gift',
    name: 'こはるの差し入れクッキー',
    emoji: '🎁',
    rarity: Rarity.normal,
    tags: ['こはる'], cast: ['こはる'],
    level: 14,
    effects: [Add(3), AddPerAdjacentTag('ファン', 2)],
  ),
  FigureDef(
    id: 'nyan_blocks',
    name: 'ぱれにゃん積み木',
    emoji: '🧱',
    rarity: Rarity.normal,
    tags: ['ぱれにゃん'],
    level: 14,
    effects: [Add(2), EveryN(3, 10)],
  ),
  FigureDef(
    id: 'hinamomo_ribbon',
    name: 'ひなもものおそろいリボン',
    emoji: '🎀',
    rarity: Rarity.rare,
    tags: ['ひなた', 'もも'], cast: ['ひなた', 'もも'],
    level: 14,
    effects: [AddPerShelfTag('もも', 3)],
  ),
  FigureDef(id: 'merch_staff', name: '物販スタッフ', emoji: '🧢', rarity: Rarity.rare, tags: ['ファン'], level: 14, effects: [Add(2), GainOnPlaced(25)]),
  FigureDef(id: 'yoru_lantern', name: 'よるのランタン', emoji: '🏮', rarity: Rarity.rare, tags: ['よる'], cast: ['よる'], level: 14, effects: [Add(3), AddIfCorner(8)]),
  FigureDef(id: 'hinamomo_figure', name: 'ひなももの限定フィギュア', emoji: '🏆', rarity: Rarity.legend, tags: ['ひなた', 'もも'], cast: ['ひなた', 'もも'], level: 14, effects: [Add(8), Luck(20)]),
  FigureDef(
    id: 'shizumomo_sign',
    name: 'しずももの金サイン色紙',
    emoji: '✍️',
    rarity: Rarity.epic,
    tags: ['もも', 'しずく', 'お金'], cast: ['しずく', 'もも'],
    level: 15,
    effects: [AddPerShelfTag('しずく', 5)],
  ),
  FigureDef(
    id: 'hinata_dress',
    name: 'ひなたの黄金ステージ衣装',
    emoji: '👑',
    rarity: Rarity.legend,
    tags: ['ひなた', 'お金'], cast: ['ひなた'],
    level: 15,
    effects: [MultShelfTag('お金', 4)],
  ),
  FigureDef(id: 'hinamomo_dome', name: 'ひなもものドームライブ', emoji: '🏟️', rarity: Rarity.legend, tags: ['ひなた', 'もも'], cast: ['ひなた', 'もも'], level: 15, effects: [MultShelfTag('ひなた', 3)]),
  FigureDef(
    id: 'gold_maneki',
    name: '金の招き猫ポーズアクスタ',
    emoji: '🐈',
    rarity: Rarity.epic,
    tags: ['ひなた', 'もも', 'お金'], cast: ['ひなた', 'もも'],
    level: 15,
    effects: [Add(2), MultAdjacentTag('お金', 3)],
  ),
  FigureDef(id: 'yoru_solo', name: 'よるのソロ衣装', emoji: '🦇', rarity: Rarity.epic, tags: ['よる'], cast: ['よる'], level: 15, effects: [Add(7), AddIfAlone(14)]),
  FigureDef(
    id: 'momo_gachikoi',
    name: 'もものガチ恋オタク',
    emoji: '😍',
    rarity: Rarity.rare,
    tags: ['ファン'], cast: ['もも'],
    level: 15,
    effects: [Add(5), AddPerAdjacentTag('もも', 3)],
  ),
  FigureDef(id: kCardId, name: 'つむぎの注意書き', emoji: '📮', rarity: Rarity.curse, tags: ['のろい'], effects: [Add(-2), OnRemovedGain(20)]),
];

final figureById = {for (final f in figures) f.id: f};
