"""シチュエーションボイス: join each scene's lines into one file.

  ~/Desktop/escape-games/tadaima-hiyori/tools/Irodori-TTS/.venv/bin/python art/asmr.py
(needs librosa + soundfile: the Irodori venv has both)

Her ordinary voice (no whisper, no ear-to-ear panning): the lines are trimmed,
evened out and laid one after another with a short breath between them, centred
as if she stands right in front of you, over a faint room tone.
Writes assets/asmr/<track>.m4a and lib/ui/asmr_timing.dart (when each line starts).
"""
import json
import subprocess
from pathlib import Path

import librosa
import numpy as np
import soundfile as sf
from scipy import signal

ROOT = Path(__file__).resolve().parent.parent
VOICE = ROOT / 'voice'
OUT = ROOT / 'assets' / 'asmr'
OUT.mkdir(parents=True, exist_ok=True)
SR = 44100
GAP = 0.75  # seconds between lines
rng = np.random.default_rng(5)


def centre(mono):
    """Right in front of you: both sides, the right a hair later for a little width."""
    r = np.concatenate([np.zeros(int(SR * 0.0004)), mono])[:len(mono)]
    return np.stack([mono, r], axis=1) * 0.8


def main():
    tracks = json.loads((VOICE / 'asmr.json').read_text())
    starts = {}
    for tid, lines in tracks.items():
        parts, t, st = [], 0.6, []
        buf = np.zeros((int(SR * 0.6), 2))
        for l in lines:
            y, sr = sf.read(VOICE / 'render' / f"{l['id']}.wav")
            if y.ndim > 1:
                y = y.mean(1)
            y = librosa.resample(y, orig_sr=sr, target_sr=SR)
            idx = np.nonzero(np.abs(y) > 0.01)[0]
            y = y[idx[0]:idx[-1] + 1]
            y = y / (np.abs(y).max() + 1e-9)
            st.append(int(t * 1000))
            buf = np.concatenate([buf, centre(y) * 0.7, np.zeros((int(SR * GAP), 2))])
            t = len(buf) / SR
        # a soft room tone under it so the silence is not dead
        room = rng.standard_normal(buf.shape) * 0.0025
        b, a = signal.butter(2, 1200 / (SR / 2))
        buf = buf + signal.lfilter(b, a, room, axis=0)
        wav = VOICE / 'render' / f'asmr_{tid}.wav'
        sf.write(wav, buf, SR)
        subprocess.run(['ffmpeg', '-loglevel', 'error', '-y', '-i', str(wav), '-af', 'loudnorm=I=-18:TP=-2',
                        '-ac', '2', '-ar', '44100', '-c:a', 'aac', '-b:a', '128k', str(OUT / f'{tid}.m4a')], check=True)
        starts[tid] = st
        print(tid, f'{len(buf) / SR:.1f}s')
    body = ''.join(f"  '{k}': {v},\n" for k, v in starts.items())
    (ROOT / 'lib' / 'ui' / 'asmr_timing.dart').write_text(
        '// Generated by art/asmr.py — do not edit.\n// track id → start of each line in ms (for the subtitles)\n'
        f'const asmrStarts = <String, List<int>>{{\n{body}}};\n')


if __name__ == '__main__':
    main()
