"""Set every sound effect's level against the music -> lib/ui/sfx_levels.dart.

  ~/tools/songgen/qc/bin/python art/sfx_levels.py     (needs pyloudnorm)
The music is -16 LUFS played at Bgm.volume 0.32, so about -26 LUFS. Each effect's
loudest 400 ms is measured and it gets the gain that puts it at its kind's target.
"""
import glob
from pathlib import Path

import numpy as np
import pyloudnorm as pyln
import soundfile as sf

ROOT = Path(__file__).resolve().parent.parent
# target loudness of the loudest moment, by kind (the music sits around -26)
UI = {'tap', 'toggle', 'place', 'pop', 'push', 'open', 'rattle', 'handle', 'reroll', 'shoot', 'buy'}
BIG = {'mult_big', 'total_big', 'pay_ok', 'pay_fail', 'payday', 'clear', 'jingle', 'over', 'unlock', 'shop', 'omen', 'siren', 'jam_win', 'jam_lose'}


def target(name):
    if name in UI:
        return -27.0
    if name.startswith('tick_'):
        return None  # one gain for the whole rising run (set from tick_14)
    if name.startswith('cheer') or name.startswith('call_'):
        return -22.0
    if name in BIG:
        return -19.0
    return -21.0  # capsules, ×2, spawns, buffs…


def peak_loudness(path):
    y, sr = sf.read(path)
    if y.ndim > 1:
        y = y.mean(1)
    n = int(sr * 0.4)
    if len(y) < n:
        y = np.concatenate([y, np.zeros(n - len(y))])
    m = pyln.Meter(sr, block_size=0.4)
    best = -99.0
    for i in range(0, len(y) - n + 1, int(sr * 0.1)):
        seg = y[i:i + n]
        if np.abs(seg).max() > 1e-4:
            best = max(best, m.integrated_loudness(seg))
    return best


def main():
    gains = {}
    files = sorted(glob.glob(str(ROOT / 'assets' / 'sfx' / '*.wav')))
    loud = {Path(f).stem: peak_loudness(f) for f in files}
    tick_gain = 10 ** ((-23.0 - loud['tick_14']) / 20)
    for name, l in loud.items():
        t = target(name)
        gains[name] = tick_gain if t is None else min(1.0, 10 ** ((t - l) / 20))
    body = ''.join(f"  '{k}': {v:.3f},\n" for k, v in gains.items())
    (ROOT / 'lib' / 'ui' / 'sfx_levels.dart').write_text(
        '// Generated by art/sfx_levels.py — do not edit.\n'
        '// Each sound effect\'s gain, set against the music (see the script for the targets).\n'
        f'const sfxGain = <String, double>{{\n{body}}};\n')
    print(len(gains), 'sounds')


if __name__ == '__main__':
    main()
