"""Turn voice/lines.json (from tool/voice_lines.dart) into Irodori-TTS jobs and
the Dart lookup table the app plays from.

  dart run tool/voice_lines.dart > voice/lines.json
  python3 voice/make_voice_jobs.py      # → voice/jobs.json, lib/ui/voice_ids.dart

Each speaker has a reference take (voice/candidates/<who>_<X>.wav, chosen from
the candidates) so every line keeps the same voice, plus a caption and a mood.
The id is a hash of who + spoken text + caption, so only changed lines re-render.
"""
import hashlib
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RENDER = HERE / 'render'

# speaker: (reference take, caption)
VOICES = {
    'ひなた': ('hinata_B', '高めで明るくまっすぐな、二十歳の女性アイドルの声。元気でテンションが高く、少し早口。'),
    'しずく': ('shizuku_A', '落ち着いた透明感のある、二十歳の女性の声。丁寧な敬語で静かに話す、クールで上品な話し方。'),
    # the bright take (D); A (おっとり、眠たげ) was tried and sounded off
    'こはる': ('koharu_D', '明るく元気いっぱいで、ふわふわ甘い、二十歳の女性アイドルの声。テンション高めで、にこにこ弾むように話す。'),
    'よる': ('yoru_A', 'いたずらっぽく小悪魔的な、二十歳の女性の声。少し低めでささやくように、からかって楽しそうに話す。'),
    # B: A sounded muffled (picked by ear from B-H)
    'もも': ('momo_B', 'とても甘い声の、二十歳の女性アイドル。妹っぽく甘えんぼで、語尾がはねる。'),
    # bright and glamorous (asked for 明るく華やか): G stays around 380 Hz, clear of ひなた / もも (~450 Hz)
    'つむぎ': ('tsumugi_G', 'つやのある明るい声の二十歳の女性。アナウンサーのように聞き取りやすく、華やかで、にこやかに話す。'),
}
MOOD = {
    'calm': '落ち着いて、やさしく説明するように。',
    'happy': 'うれしそうに、にこにこして。',
    'excited': 'とても興奮して、きらきらした笑顔で。',
    'surprise': 'びっくりして、目を丸くして。',
    'deadpan': 'ジト目で、あきれたように淡々と。',
    'angry': 'ぷんぷん怒って、頬をふくらませて。',
}

# シチュエーションボイス: her usual voice, talking to the one fan right in front of her
SCENE = 'すぐ目の前にいる大切なファンに、ふたりきりで語りかけるように。気持ちをこめて、表情豊かに、自然な会話のテンポで。'

# Spoken text fixes (TTS pitfalls). Display text stays as written.
READINGS = [
    ('×2', '2倍'),
    ('推し祭壇', 'おしさいだん'),
    ('SSR', 'エスエスアール'),
    ('5回', '五回'),
    ('「', ''), ('」', ''),
    ('！ ', '！'), ('？ ', '？'),
]


# Lines whose take came out wrong with the default seed (checked by ASR).
SEED = {
    'こはるのアクスタの、となりに置いてください': 23,  # となり → トネリ
}


def spoken(text: str) -> str:
    s = text
    for a, b in READINGS:
        s = s.replace(a, b)
    s = re.sub(r'^[…。、\s]+|[…\s]+$', '', s)
    return s


def main() -> None:
    lines = json.loads((HERE / 'lines.json').read_text())
    jobs, table, seen, asmr = [], {}, set(), {}
    for l in lines:
        who, text, mood = l['who'], l['text'], l['mood']
        ref, cap = VOICES[who]
        caption = cap + (SCENE if mood == 'scene' else MOOD[mood])
        say = spoken(text)
        seed = SEED.get(text, 11)
        vid = hashlib.sha1(f'{who}|{say}|{caption}{"" if seed == 11 else seed}'.encode()).hexdigest()[:10]
        if mood == 'scene':
            asmr.setdefault(l['track'], []).append({'id': vid, 'text': text})
        else:
            table[f'{who}|{text}'] = vid
        if vid in seen:
            continue
        seen.add(vid)
        jobs.append({'out': str(RENDER / f'{vid}.wav'), 'text': say, 'caption': caption,
                     'ref': str(HERE / 'candidates' / f'{ref}.wav'), 'seed': seed,
                     'duration_scale': 0.92 if mood == 'scene' else 0.85, 'kind': 'scene' if mood == 'scene' else 'line', 'who': who})
    (HERE / 'jobs.json').write_text(json.dumps(jobs, ensure_ascii=False, indent=1))
    (HERE / 'asmr.json').write_text(json.dumps(asmr, ensure_ascii=False, indent=1))
    body = ''.join(f"  {json.dumps(k, ensure_ascii=False)}: '{v}',\n" for k, v in sorted(table.items()))
    (ROOT / 'lib' / 'ui' / 'voice_ids.dart').write_text(
        '// Generated by voice/make_voice_jobs.py — do not edit.\n'
        '// "speaker|line" → assets/voice/<id>.m4a\n'
        f'const voiceIds = <String, String>{{\n{body}}};\n')
    print(len(jobs), 'jobs,', len(table), 'lines')


if __name__ == '__main__':
    main()
